import type { TestPlan, UrlPart, Value } from './normalize';

/** First line of every generated file; the hash detects in-place edits. */
export const GENERATED_MARK = '// GENERATED by session-gen';

export function header(plan: TestPlan, source: string): string[] {
  const m = plan.meta;
  return [
    '// Do not edit in place: regenerating overwrites this file, and the generator refuses',
    '// to overwrite a file that was changed. To keep it, copy it into your owned spec folder.',
    `// Source: ${source} (${[`${m.mode} mode`, m.appVersion && `app ${m.appVersion}`, m.environment, m.startedAt].filter(Boolean).join(', ')})`,
    ...plan.notes.map((n) => `// NOTE: ${n}`),
  ];
}

export const str = (s: string): string => JSON.stringify(s);

export function camel(id: string): string {
  const words = id.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const key = words
    .map((w, i) => (i === 0 ? w[0].toLowerCase() : w[0].toUpperCase()) + w.slice(1))
    .join('');
  if (!key) return 'el';
  return /^\d/.test(key) ? `_${key}` : key;
}

/** Stable, collision-free constant names for each data-attribute value. */
export function selectorKeys(targets: string[]): Map<string, string> {
  const used = new Set<string>();
  const keys = new Map<string, string>();
  for (const id of [...targets].sort()) {
    const base = camel(id);
    let key = base;
    for (let n = 2; used.has(key); n++) key = `${base}${n}`;
    used.add(key);
    keys.set(id, key);
  }
  return keys;
}

const escapeRe = (s: string): string => s.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');

/**
 * Regex literal for a path pattern. 'pathname' anchors at the end of a pathname;
 * 'url' matches inside a full URL that may carry a query string or fragment.
 */
export function pathRegex(pattern: string, against: 'pathname' | 'url'): string {
  const body = pattern
    .split('/')
    .map((s) => (s === '*' || s === ':id' ? '[^/]+' : escapeRe(s)))
    .join('\\/');
  return against === 'pathname' ? `/${body}$/` : `/${body}(?:[?#]|$)/`;
}

export function urlExpr(parts: UrlPart[]): string {
  if (parts.every((p) => typeof p === 'string')) return str(parts.join('/'));
  const body = parts
    .map((p) => (typeof p === 'string' ? p.replace(/[`\\$]/g, '\\$&') : '${data.' + p.placeholder + '}'))
    .join('/');
  return '`' + body + '`';
}

export const valueExpr = (v: Value): string => ('literal' in v ? str(v.literal) : `data.${v.placeholder}`);

export function dataBlock(plan: TestPlan): string[] {
  if (plan.placeholders.length === 0) return [];
  return [
    '// Fill these in before running. Use synthetic data only.',
    'const data = {',
    ...plan.placeholders.map((p) => `  ${p.key}: '', // TODO: ${p.hint}`),
    '};',
    '',
  ];
}
